---
title: "data cleaning"
---

Sampling Rate is 5 times per second. Every 0.2 seconds, a reading is recorded. double check

```{r}
#| label: load-packages

library(tidyverse)
library(tidymodels)
```

```{r}
#| label: read-data

rawAccelerationW <- read_csv("/Volumes/T7 Shield/Whale_ML_Project/data/raw/accelerationw.csv", col_names = FALSE)
```

```{r}
#| label: clean-data

gravity = 9.80665

accelerationW <- rawAccelerationW |>
  rename(
    x = X1,
    y = X2,
    z = X3
  ) |>
  mutate(
    x = x * gravity,     #convert from G to meters per second squared
    y = y * gravity,
    z = z * gravity
  )


```

```{r}
#| label: condense-data-by-5 

#Sampling rate in terms of time unknown

accelerationWCondensed <- accelerationW |>
  mutate(group = ceiling(row_number() / 5)) |>  # Create a grouping variable
  group_by(group) |>
  summarise(across(everything(), mean, na.rm = TRUE)) |> 
  select(-group)


```

```{r}
#| label: accel-change
accelerationWCondensed <- accelerationWCondensed |>
  mutate(
    deltaX = x - lag(x),
    deltaY = y - lag(y),
    deltaZ = z - lag(z),
    magA = sqrt(x^2 + y^2 + z^2),
    deltamagA = magA - lag(magA)
  ) 
         


```

```{r}

ggplot(accelerationWCondensed, aes(time_secs, x)) +
  geom_point()

```
